[[constraint]]
  name = "github.com/docker/docker"
  version = "^1.3.7"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "github.com/aws/aws-sdk-go"

[prune]
  go-tests = true
  unused-packages = true
